# Generated by Django 4.1.3 on 2022-12-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=100, null=True)),
                ('data', models.FileField(upload_to='data/')),
            ],
        ),
    ]
