# Generated by Django 4.1.3 on 2022-12-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='data',
            field=models.FileField(upload_to='mineGUI/WebApp/data/'),
        ),
    ]
