# Generated by Django 4.1.3 on 2023-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_proyecto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='data',
            field=models.FileField(upload_to='WebApp/data/'),
        ),
    ]
